/**
 * API de Gestion de la Trésorerie
 *
 * Contact: support@agencevoyage.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BilanDto { 
    id?: number;
    realise?: number;
    pourcentageRealise?: number;
    pourcentageFram?: number;
    pourcentageAssurance?: number;
    framCroisieres?: number;
    autresTo?: number;
    assurances?: number;
    totalPrimesBrutes?: number;
    vendeurNom?: string;
    vendeurPrenom?: string;
    userId?: number;
}

