/**
 * API de Gestion de la Trésorerie
 *
 * Contact: support@agencevoyage.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Person { 
    id?: number;
    name?: string;
    city?: string;
    phoneNumber?: string;
}

