/**
 * API de Gestion de la Trésorerie
 *
 * Contact: support@agencevoyage.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgenceVoyage } from './agenceVoyage';


export interface User { 
    id?: number;
    nom?: string;
    prenom?: string;
    email?: string;
    password?: string;
    role?: string;
    token?: string;
    agence?: AgenceVoyage;
}

