/**
 * API de Gestion de la Trésorerie
 *
 * Contact: support@agencevoyage.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VenteDto { 
    id?: number;
    nom?: string;
    prenom?: string;
    numeroDossier?: string;
    pax?: number;
    dateValidation?: string;
    dateDepart?: string;
    tourOperateur?: string;
    venteTotal?: number;
    assurance?: boolean;
    montantAssurance?: number;
    fraisAgence?: number;
    totalSansAssurance?: number;
    userId?: number;
}

