/**
 * API de Gestion de la Trésorerie
 *
 * Contact: support@agencevoyage.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VentesParJourDto { 
    date?: string;
    nombreVentes?: number;
    totalVentes?: number;
}

