/**
 * API de Gestion de la Trésorerie
 *
 * Contact: support@agencevoyage.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { VenteDtoTransactionDate } from './venteDtoTransactionDate';


export interface Vente { 
    id?: number;
    version?: number;
    venteTotal?: number;
    nom: string;
    prenom: string;
    numeroDossier: string;
    pax?: number;
    dateValidation?: string;
    dateDepart?: string;
    tourOperateur: string;
    montantAssurance?: number;
    fraisAgence?: number;
    totalSansAssurance?: number;
    assurance?: boolean;
    transactionDate?: VenteDtoTransactionDate;
    user?: User;
}

