name: Generate OpenAPI Client

on:
  push:
    branches:
      - main

jobs:
  generate_openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Generate API client
        run: openapi-generator-cli generate -i https://promovacbackend-production.up.railway.app/v3/api-docs -g typescript-angular -o src/back

      - name: Commit generated files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add src/back
          git commit -m "Update OpenAPI client" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.PROMOVC }}@github.com/Elias0900/tresoreriefront.git main
